[package]
name = "rust-kafka-consumer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = { version = "0.29.0", features = ["ssl"] }
serde_json = "1.0.95"
